### ISSUE TITLE
Default constructor suggestion

### ISSUE THREAD

**Issue by jgottula** [bgottula/fixed#11]
Suggest setting width to an "invalid" value in the default constructor; on first assignment, this is set to the width of the rhs.

**Comment by bgottula** [comment]
If I use an invalid width in the default constructor, that forces me to check the invalid flag every time any operation is performed which would be an unfortunate performance penalty. Perhaps I can still use a valid default width in the default constructor, but set `m_initialized(false)`, which would allow the width to be muted on the first (and only first) invocation of the assignment operator. I'm not super excited about either option, to be honest. I really wish I didn't need the default constructor at all. Maybe there's still a way around it.

**Comment by jgottula** [comment]
The cleanest solution as far as I can tell is to do the following:
- Don't have a default constructor at all
- Use `std::vector` when you want an array of class instances: it
  provides a way to construct its array values as copies of an existing class
  instance
- Don't use regular arrays or `operator new []` for class instances

**Comment by bgottula** [comment]
I like that solution! It looks like that "fill constructor" is also
available for std::deque which might provide a suitable replacement for the
internals of my homemade fifo template object. Or std::vector might work
for that too.

**Comment by bgottula** [comment]
Removed default constructor in 42a5b01e7da21ddd26694b1f7accda7e5f5b67dd
