### ISSUE TITLE
Enhancify: add support for user-defined literals

### ISSUE THREAD

**Issue by jgottula** [bgottula/fixed#16]
C++11 adds the ability for classes to implement [user-defined literals](http://en.wikipedia.org/wiki/C%2B%2B11#User-defined_literals). Hypothetically, with this feature, you could make it so that writing `1.234_fxp` anywhere in a code file will create a `Fxp` literal with that value.

This may not work so well when you want multiple values (e.g. value and bit length, or real and imaginary part). Deserves some investigation.

**Comment by bgottula** [comment]
This is very cool, but because user defined literals don't support multiple arguments I don't think they're a good fit for these classes. Fortunately it's not too cumbersome to type out `Fxp(4, 8)` or `CFxp(-1, 3, 8)` using the short-form aliases of the class names.
