### ISSUE TITLE
Look into the explicit keyword

### ISSUE THREAD

**Issue by jgottula** [bgottula/fixed#17]
C++ lets you use the [explicit](http://en.cppreference.com/w/cpp/language/explicit) keyword in some cases to avoid copying of classes when you don't want it. You may want to use this for `FixedPoint`/`ComplexFixedPoint`.

**Comment by jgottula** [comment]
It also avoids some implicit type conversions.

**Comment by bgottula** [comment]
Looked into this briefly, but don't fully understand the scenarios where it would be a problem. Decided to do nothing unless it becomes a problem.
